// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kajay.Workflow.Host.Persistence.Migrations;

/// <inheritdoc />
public partial class AddDefinitionAuthoring : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "managed_definitions",
            columns: table => new
            {
                TenantId = table.Column<string>(type: "text", nullable: false),
                Name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                CreatedBy = table.Column<string>(type: "text", nullable: false),
                CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_managed_definitions", x => new { x.TenantId, x.Name });
            });

        migrationBuilder.CreateTable(
            name: "definition_drafts",
            columns: table => new
            {
                TenantId = table.Column<string>(type: "text", nullable: false),
                ManagedDefinitionName = table.Column<string>(type: "character varying(128)", nullable: false),
                DefinitionJson = table.Column<string>(type: "jsonb", nullable: false),
                DefinitionDigest = table.Column<string>(type: "character varying(71)", maxLength: 71, nullable: false),
                Version = table.Column<long>(type: "bigint", nullable: false),
                UpdatedBy = table.Column<string>(type: "text", nullable: false),
                UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_definition_drafts", x => new { x.TenantId, x.ManagedDefinitionName });
                table.ForeignKey(
                    name: "FK_definition_drafts_managed_definitions_TenantId_ManagedDefin~",
                    columns: x => new { x.TenantId, x.ManagedDefinitionName },
                    principalTable: "managed_definitions",
                    principalColumns: new[] { "TenantId", "Name" },
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateTable(
            name: "definition_revisions",
            columns: table => new
            {
                TenantId = table.Column<string>(type: "text", nullable: false),
                ManagedDefinitionName = table.Column<string>(type: "character varying(128)", nullable: false),
                Number = table.Column<long>(type: "bigint", nullable: false),
                SourceDraftVersion = table.Column<long>(type: "bigint", nullable: false),
                DefinitionJson = table.Column<string>(type: "jsonb", nullable: false),
                DefinitionDigest = table.Column<string>(type: "character varying(71)", maxLength: 71, nullable: false),
                CreatedBy = table.Column<string>(type: "text", nullable: false),
                CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_definition_revisions", x => new { x.TenantId, x.ManagedDefinitionName, x.Number });
                table.ForeignKey(
                    name: "FK_definition_revisions_managed_definitions_TenantId_ManagedDe~",
                    columns: x => new { x.TenantId, x.ManagedDefinitionName },
                    principalTable: "managed_definitions",
                    principalColumns: new[] { "TenantId", "Name" },
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(
            name: "IX_definition_revisions_TenantId_ManagedDefinitionName_SourceD~",
            table: "definition_revisions",
            columns: new[] { "TenantId", "ManagedDefinitionName", "SourceDraftVersion" },
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "definition_drafts");

        migrationBuilder.DropTable(
            name: "definition_revisions");

        migrationBuilder.DropTable(
            name: "managed_definitions");
    }
}
