// <auto-generated />
using System;
using Kajay.Workflow.Host.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kajay.Workflow.Host.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260807113840_AddEnvironmentCatalog")]
    partial class AddEnvironmentCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.ActivationRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentName")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ManagedDefinitionName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDigest")
                        .IsRequired()
                        .HasColumnType("character varying(71)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "EnvironmentName", "ManagedDefinitionName");

                    b.HasIndex("TenantId", "ReleaseDigest");

                    b.ToTable("activations", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionDraftRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("ManagedDefinitionName")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DefinitionDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "ManagedDefinitionName");

                    b.ToTable("definition_drafts", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionReleaseProvenanceRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDigest")
                        .HasColumnType("character varying(71)");

                    b.Property<string>("ManagedDefinitionName")
                        .HasColumnType("character varying(128)");

                    b.Property<long>("RevisionNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "ReleaseDigest", "ManagedDefinitionName", "RevisionNumber");

                    b.HasIndex("TenantId", "ManagedDefinitionName", "RevisionNumber");

                    b.ToTable("definition_release_provenance", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionReleaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Bundle")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("ConformanceVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagedDefinitionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("RequiredBindings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SurveyDefinitionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkflowJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ManagedDefinitionName", "VersionLabel")
                        .IsUnique();

                    b.ToTable("definition_releases", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionRevisionRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("ManagedDefinitionName")
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefinitionDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("SourceDraftVersion")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "ManagedDefinitionName", "Number");

                    b.HasIndex("TenantId", "ManagedDefinitionName", "SourceDraftVersion")
                        .IsUnique();

                    b.ToTable("definition_revisions", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.EnvironmentBindingRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentName")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "EnvironmentName", "Name");

                    b.ToTable("environment_bindings", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.EnvironmentRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Name");

                    b.HasIndex("TenantId", "Position", "Name");

                    b.ToTable("environments", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("TenantId", "Key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.ManagedDefinitionRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Name");

                    b.ToTable("managed_definitions", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.ManagementAuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Subject", "OccurredAt");

                    b.ToTable("management_audit_events", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EffectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAt");

                    b.HasIndex("TenantId", "EffectId")
                        .IsUnique();

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.ScheduledActionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DueAt");

                    b.HasIndex("TenantId", "ActionId")
                        .IsUnique();

                    b.ToTable("scheduled_actions", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.WorkflowAuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WorkflowInstanceId", "Sequence")
                        .IsUnique();

                    b.ToTable("workflow_audit_events", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.WorkflowInstanceRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveStepKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ManagedDefinitionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NextAuditSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ReleaseDigest")
                        .IsRequired()
                        .HasColumnType("character varying(71)");

                    b.Property<string>("ResponseSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "EnvironmentName");

                    b.HasIndex("TenantId", "ReleaseDigest");

                    b.HasIndex("TenantId", "Status", "UpdatedAt");

                    b.ToTable("workflow_instances", (string)null);
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.ActivationRecord", b =>
                {
                    b.HasOne("Kajay.Workflow.Host.Persistence.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EnvironmentName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kajay.Workflow.Host.Persistence.DefinitionReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReleaseDigest")
                        .HasPrincipalKey("TenantId", "Digest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionDraftRecord", b =>
                {
                    b.HasOne("Kajay.Workflow.Host.Persistence.ManagedDefinitionRecord", null)
                        .WithOne()
                        .HasForeignKey("Kajay.Workflow.Host.Persistence.DefinitionDraftRecord", "TenantId", "ManagedDefinitionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionReleaseProvenanceRecord", b =>
                {
                    b.HasOne("Kajay.Workflow.Host.Persistence.DefinitionReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReleaseDigest")
                        .HasPrincipalKey("TenantId", "Digest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kajay.Workflow.Host.Persistence.DefinitionRevisionRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ManagedDefinitionName", "RevisionNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.DefinitionRevisionRecord", b =>
                {
                    b.HasOne("Kajay.Workflow.Host.Persistence.ManagedDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ManagedDefinitionName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.EnvironmentBindingRecord", b =>
                {
                    b.HasOne("Kajay.Workflow.Host.Persistence.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EnvironmentName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kajay.Workflow.Host.Persistence.WorkflowInstanceRecord", b =>
                {
                    b.HasOne("Kajay.Workflow.Host.Persistence.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EnvironmentName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kajay.Workflow.Host.Persistence.DefinitionReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReleaseDigest")
                        .HasPrincipalKey("TenantId", "Digest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
