// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kajay.Workflow.Host.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialWorkflowHost : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "definition_releases",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    Digest = table.Column<string>(type: "character varying(71)", maxLength: 71, nullable: false),
                    ManagedDefinitionName = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    VersionLabel = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    ConformanceVersion = table.Column<int>(type: "integer", nullable: false),
                    WorkflowJson = table.Column<string>(type: "jsonb", nullable: false),
                    SurveyDefinitionsJson = table.Column<string>(type: "jsonb", nullable: false),
                    RequiredBindings = table.Column<string[]>(type: "text[]", nullable: false),
                    Bundle = table.Column<byte[]>(type: "bytea", nullable: false),
                    InstalledAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_definition_releases", x => x.Id);
                    table.UniqueConstraint("AK_definition_releases_TenantId_Digest", x => new { x.TenantId, x.Digest });
                });

            migrationBuilder.CreateTable(
                name: "environment_bindings",
                columns: table => new
                {
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    EnvironmentName = table.Column<string>(type: "text", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Reference = table.Column<string>(type: "text", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_environment_bindings", x => new { x.TenantId, x.EnvironmentName, x.Name });
                });

            migrationBuilder.CreateTable(
                name: "idempotency_records",
                columns: table => new
                {
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    Key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    Operation = table.Column<string>(type: "text", nullable: false),
                    RequestHash = table.Column<string>(type: "character varying(71)", maxLength: 71, nullable: false),
                    ResultJson = table.Column<string>(type: "jsonb", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_idempotency_records", x => new { x.TenantId, x.Key });
                });

            migrationBuilder.CreateTable(
                name: "management_audit_events",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    Subject = table.Column<string>(type: "text", nullable: false),
                    EventType = table.Column<string>(type: "text", nullable: false),
                    PayloadJson = table.Column<string>(type: "jsonb", nullable: false),
                    ActorId = table.Column<string>(type: "text", nullable: false),
                    OccurredAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_management_audit_events", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "outbox_messages",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    WorkflowInstanceId = table.Column<Guid>(type: "uuid", nullable: false),
                    EffectId = table.Column<string>(type: "text", nullable: false),
                    EffectType = table.Column<string>(type: "text", nullable: false),
                    PayloadJson = table.Column<string>(type: "jsonb", nullable: false),
                    Status = table.Column<string>(type: "text", nullable: false),
                    Attempts = table.Column<int>(type: "integer", nullable: false),
                    AvailableAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    LeaseToken = table.Column<Guid>(type: "uuid", nullable: true),
                    LeaseUntil = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastError = table.Column<string>(type: "character varying(2048)", maxLength: 2048, nullable: true),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    DeliveredAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_outbox_messages", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "scheduled_actions",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    WorkflowInstanceId = table.Column<Guid>(type: "uuid", nullable: false),
                    ActionId = table.Column<string>(type: "text", nullable: false),
                    StepKey = table.Column<string>(type: "text", nullable: false),
                    Status = table.Column<string>(type: "text", nullable: false),
                    DueAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    Attempts = table.Column<int>(type: "integer", nullable: false),
                    LeaseToken = table.Column<Guid>(type: "uuid", nullable: true),
                    LeaseUntil = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastError = table.Column<string>(type: "character varying(2048)", maxLength: 2048, nullable: true),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CompletedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_scheduled_actions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "workflow_audit_events",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    WorkflowInstanceId = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<long>(type: "bigint", nullable: false),
                    EventType = table.Column<string>(type: "text", nullable: false),
                    PayloadJson = table.Column<string>(type: "jsonb", nullable: false),
                    ActorId = table.Column<string>(type: "text", nullable: false),
                    OccurredAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_workflow_audit_events", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "activations",
                columns: table => new
                {
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    EnvironmentName = table.Column<string>(type: "text", nullable: false),
                    ManagedDefinitionName = table.Column<string>(type: "text", nullable: false),
                    ReleaseDigest = table.Column<string>(type: "character varying(71)", nullable: false),
                    Version = table.Column<long>(type: "bigint", nullable: false),
                    ApprovedBy = table.Column<string>(type: "text", nullable: true),
                    ActivatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_activations", x => new { x.TenantId, x.EnvironmentName, x.ManagedDefinitionName });
                    table.ForeignKey(
                        name: "FK_activations_definition_releases_TenantId_ReleaseDigest",
                        columns: x => new { x.TenantId, x.ReleaseDigest },
                        principalTable: "definition_releases",
                        principalColumns: new[] { "TenantId", "Digest" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "workflow_instances",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TenantId = table.Column<string>(type: "text", nullable: false),
                    EnvironmentName = table.Column<string>(type: "text", nullable: false),
                    ManagedDefinitionName = table.Column<string>(type: "text", nullable: false),
                    ReleaseDigest = table.Column<string>(type: "character varying(71)", nullable: false),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ActiveStepKey = table.Column<string>(type: "text", nullable: false),
                    ResponseSnapshotJson = table.Column<string>(type: "jsonb", nullable: true),
                    Version = table.Column<long>(type: "bigint", nullable: false),
                    NextAuditSequence = table.Column<long>(type: "bigint", nullable: false),
                    StartedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CompletedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_workflow_instances", x => new { x.TenantId, x.Id });
                    table.ForeignKey(
                        name: "FK_workflow_instances_definition_releases_TenantId_ReleaseDige~",
                        columns: x => new { x.TenantId, x.ReleaseDigest },
                        principalTable: "definition_releases",
                        principalColumns: new[] { "TenantId", "Digest" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_activations_TenantId_ReleaseDigest",
                table: "activations",
                columns: new[] { "TenantId", "ReleaseDigest" });

            migrationBuilder.CreateIndex(
                name: "IX_definition_releases_TenantId_ManagedDefinitionName_VersionL~",
                table: "definition_releases",
                columns: new[] { "TenantId", "ManagedDefinitionName", "VersionLabel" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_management_audit_events_TenantId_Subject_OccurredAt",
                table: "management_audit_events",
                columns: new[] { "TenantId", "Subject", "OccurredAt" });

            migrationBuilder.CreateIndex(
                name: "IX_outbox_messages_Status_AvailableAt",
                table: "outbox_messages",
                columns: new[] { "Status", "AvailableAt" });

            migrationBuilder.CreateIndex(
                name: "IX_outbox_messages_TenantId_EffectId",
                table: "outbox_messages",
                columns: new[] { "TenantId", "EffectId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_scheduled_actions_Status_DueAt",
                table: "scheduled_actions",
                columns: new[] { "Status", "DueAt" });

            migrationBuilder.CreateIndex(
                name: "IX_scheduled_actions_TenantId_ActionId",
                table: "scheduled_actions",
                columns: new[] { "TenantId", "ActionId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_workflow_audit_events_TenantId_WorkflowInstanceId_Sequence",
                table: "workflow_audit_events",
                columns: new[] { "TenantId", "WorkflowInstanceId", "Sequence" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_workflow_instances_TenantId_ReleaseDigest",
                table: "workflow_instances",
                columns: new[] { "TenantId", "ReleaseDigest" });

            migrationBuilder.CreateIndex(
                name: "IX_workflow_instances_TenantId_Status_UpdatedAt",
                table: "workflow_instances",
                columns: new[] { "TenantId", "Status", "UpdatedAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "activations");

            migrationBuilder.DropTable(
                name: "environment_bindings");

            migrationBuilder.DropTable(
                name: "idempotency_records");

            migrationBuilder.DropTable(
                name: "management_audit_events");

            migrationBuilder.DropTable(
                name: "outbox_messages");

            migrationBuilder.DropTable(
                name: "scheduled_actions");

            migrationBuilder.DropTable(
                name: "workflow_audit_events");

            migrationBuilder.DropTable(
                name: "workflow_instances");

            migrationBuilder.DropTable(
                name: "definition_releases");
        }
    }
}
