import type {
  CreatorButtonProps,
  CreatorCheckboxProps,
  CreatorComponents,
  CreatorInputProps,
  CreatorSelectProps,
  CreatorTextareaProps,
} from '@kajay/creator-react';
import type { ReactElement } from 'react';
import { Button as ShadcnButton } from '@/components/ui/button';
import { Checkbox as ShadcnCheckbox } from '@/components/ui/checkbox';
import { Input as ShadcnInput } from '@/components/ui/input';
import {
  Select as ShadcnSelect,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea as ShadcnTextarea } from '@/components/ui/textarea';

/**
 * The Creator drawn with this application's own design system — ADR-0022's claim, tested.
 *
 * Every component below comes from `src/components/ui/`, generated by `shadcn add` and
 * owned by this repository the way a real adopter owns theirs. Nothing here reaches into
 * Kajay's internals; the entire integration is the value exported at the bottom.
 *
 * **What the ADR predicted, and where it was wrong.** It said a shadcn adapter would be
 * "a re-export, not a translation layer." Four of the five nearly are. The fifth is not,
 * and the reason is structural rather than cosmetic — see {@link Select}.
 */

/**
 * A re-export in all but name.
 *
 * shadcn's Button spreads onto a native `<button>`, so the pointer and key handlers K2's
 * drag gesture depends on arrive without this file mentioning them. That is exactly the
 * property the primitive contract documents and asks for.
 */
function Button({ children, ...props }: CreatorButtonProps): ReactElement {
  return (
    <ShadcnButton variant="outline" size="sm" {...props}>
      {children}
    </ShadcnButton>
  );
}

/**
 * A three-line shim: Kajay says `onValueChange`, the DOM says `onChange`.
 *
 * Worth noting rather than complaining about — `onValueChange` is the right shape for a
 * library that does not want to hand out `ChangeEvent`, and unwrapping `event.target.value`
 * is the smallest possible adapter.
 */
function Input({ onValueChange, ...props }: CreatorInputProps): ReactElement {
  return (
    <ShadcnInput
      {...props}
      onChange={(event) => {
        onValueChange(event.target.value);
      }}
    />
  );
}

function Textarea({ onValueChange, ...props }: CreatorTextareaProps): ReactElement {
  return (
    <ShadcnTextarea
      {...props}
      onChange={(event) => {
        onValueChange(event.target.value);
      }}
    />
  );
}

/**
 * The one true re-export. `checked`/`onCheckedChange` is Radix's own shape, unchanged.
 */
function Checkbox(props: CreatorCheckboxProps): ReactElement {
  return <ShadcnCheckbox {...props} />;
}

/**
 * **The finding.** This one is a genuine translation layer, and no rewording fixes it.
 *
 * Kajay's `Select` takes `options` — *data*. Radix's Select takes *composition*: a trigger,
 * a value, a content panel and an item per choice. So the adapter has to build the tree,
 * which means it also has to make decisions Kajay did not delegate — what the trigger looks
 * like when nothing is chosen, where the panel is portalled, how long the list may get.
 *
 * That is not a defect in either design. It is the difference between a prop contract that
 * assumes a native `<select>` and an ecosystem that abandoned native selects years ago. The
 * question ADR-0022 has to answer, and could not have answered before this file existed, is
 * whether the *data* shape is the right one for a seam whose entire purpose is to hand
 * drawing to somebody else.
 */
function Select({
  value,
  options,
  onValueChange,
  disabled,
  className,
  id,
  ...rest
}: CreatorSelectProps): ReactElement {
  // `disabled` is spread conditionally rather than passed: Kajay types it `boolean |
  // undefined` and Radix types it `boolean`, and under this workspace's
  // `exactOptionalPropertyTypes` those are genuinely different. Every adapter written
  // against a third-party component meets this, and the answer is a conditional spread
  // rather than a cast.
  return (
    <ShadcnSelect
      value={value}
      onValueChange={onValueChange}
      {...(disabled === undefined ? {} : { disabled })}
    >
      <SelectTrigger id={id} className={className} size="sm" {...rest}>
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {options.map((option) => (
          <SelectItem key={option.value} value={option.value}>
            {option.label}
          </SelectItem>
        ))}
      </SelectContent>
    </ShadcnSelect>
  );
}

/** The whole integration: one object, passed to `<SurveyCreator components={…} />`. */
export const KAJAY_CREATOR_COMPONENTS: CreatorComponents = {
  Button,
  Input,
  Textarea,
  Checkbox,
  Select,
};
