<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Kajay.Workflow.Host</AssemblyName>
    <RootNamespace>Kajay.Workflow.Host</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="All" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WorkOS.net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Kajay.Core/Kajay.Core.csproj" />
  </ItemGroup>
</Project>
